volumes:
  db_volume:
    driver: local
  redis_volume:
    driver: local

version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/e2e/Dockerfile
    container_name: fleetyards
    command: bash -c "bundle exec rails db:create db:schema:load db:seed webpacker:compile assets:precompile && bundle exec puma -C config/puma.rb"
    ports:
      - "8270:3000"
    environment:
      - DATABASE_URL=postgresql://root:root@db/fleetyards
      - TEST_SEEDS=1
      - RAILS_SERVE_STATIC_FILES=1
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - API_URL=http://localhost:3000/api/v1
      - FRONTEND_HOST=http://localhost:3000
      - REDIS_URL=redis://redis:6379
      - RAVEN_DSN=
      - CI=1
      - CABLE_URL=ws://localhost:3000/cable
    depends_on:
      - db
      - redis

  db:
    image: postgres:9.5.16-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - db_volume:/var/lib/postgresql/

  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis_volume:/data
